### ISSUE TITLE
The documentation doesn't make "phasing" very clear.

### ISSUE THREAD

**Issue by cullylarson** [Goel25/tritris#7]
I've been playing the game for a bit. I still don't understand when a piece is going to phase and when it isn't. I often think it will and it doesn't, or vice versa. I've read the How to Play section on Phasing, but I still don't get it. For example, what does this mean:

> Instead, all phases can be performed by holding each key (rotate can now be held to become "charged").

What is "each key"? What is "charged"?

Or this:

> A piece will always move to the next location as long as the next location is valid (no intersecting triangles).

It says "no intersecting triangles", but the examples show pieces phasing through intersecting triangles to get to a lower position.

There's also mention of holding the rotate key. But when I press the key down, the rotation happens immediately. It doesn't happen on key up. So do I press the key, get a rotation, and then hold it?

**Comment by Goel25** [comment]
Thank you for playing! I apologize if the tutorial is unclear. Below is an explanation to each of your questions. If this clears it up, do you have any suggestions to make the tutorial clearer? However, I do not want to make it as lengthy as below.

> What is "each key"? 

Each key is a control (left, right, down, Z, X, or whatever they are set to). You can hold multiple keys at once to move in multiple directions at once. For example, holding clockwise rotate and right (X and right arrow) will try to move a piece in both those directions. If where it tries to move is not blocked (further explanation on that below), it will move there. It is called phasing because it is possible for it to pass through some triangles in the way. All that matters is that where it tries to move is not blocked.

> What is "charged"?

Charged refers to the rotation buffer. If you hold the rotate button (Z or X), and it is unable to rotate (something is blocking it), it becomes charged. As long as you keep holding that rotation key it will stay charged. Once the piece is able to rotate (it has moved down or you pressed left/right), the the piece will rotate (and move down or left/right, depending on which happened) and the rotation will no longer be charged.

> A piece will always move to the next location as long as the next location is valid (no intersecting triangles).

Intersecting triangles means that they cannot fit in the same square. So 2 triangles are intersecting if they are in the same position, or on is a 90 degree rotation of the other. They are **not** intersecting if they are opposite.

For example,
If the triangles look like this:  ◤◢   (of course in the same grid cell), they are not intersecting.
If the triangles look like this: ◤ ◣ (in the same grid cell), then they are intersecting, and you can **not** phase there.

> There's also mention of holding the rotate key.

This refers to the aforementioned rotation buffer. When you press it down, if it cannot rotate immediately, it becomes charged. On key up, it will no longer be charged.

If you still have questions on phasing, strategies or other mechanics, come talk on the [discord](https://discord.gg/NUKWP6UCHF). We have a channel dedicated to showing phases, which could help you see what is possible.

**Comment by cullylarson** [comment]
Thanks for the info! To clarify, I wasn't asking so much to get answers here, but to describe what was confusing, in case it's helpful if the documentation ever gets updated.

**Comment by Goel25** [comment]
I'm glad you asked the question. I will try to update the documentation soon.
